import './globals.css'
import '@uploadthing/react/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ToasterProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from './api/uploadthing/core';
import { extractRouterConfig } from "uploadthing/server";

// import { ourFileRouter } from "~/app/apij/uploadthing/core";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Roboautomators LMS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>

        <ConfettiProvider />
        <ToasterProvider />
           <NextSSRPlugin
     
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        {children}
        </body>
    </html>
    </ClerkProvider>
  )
}
